### ISSUE TITLE
Built In wss sessions is creating too many trends

### ISSUE THREAD

**Issue by mkadirtan** [grafana/xk6-websockets#33]
Hi, the built-in metrics for ws_session_duration_seconds etc. include the websocket url. Which is great, but it also includes the query parameters. I'm testing for a socket.io server and the query parameter include user token. That causes k6 to create as many histograms as there are different users. Is it possible to ignore query parameters for this? Maybe we can add this as an option to environment variable?

**Comment by olegbespalov** [comment]
Hi @mkadirtan 

Thanks for the feedback!

You're right, and we have to introduce some workarounds for that.

Let us come up with a decision on how to handle it better (aligning with the core [grafana/k6 which](https://github.com/grafana/k6) has similar changes) and probably implement it :relaxed:

**Comment by mkadirtan** [comment]
Thanks for the reply, maybe we can use this issue to track progress

**Comment by konovalovsergey** [comment]
Hi @olegbespalov 
It's reasonable to follow logic of k6 after v0.41.0 (https://github.com/grafana/k6/pull/2703) - replace "url" tag with "name" tag if it exists.
What you will say to that?

**Comment by konovalovsergey** [comment]
Сan I help with the implementation of this functionality? If this is the right direction. Task doesn't look very difficult.

**Comment by olegbespalov** [comment]
Hey @konovalovsergey ! Thanks for offering the help! :relaxed: 

Let me quickly confirm with the team that this is the direction in which we want to evolve, and I (or anybody else from the core team) will get back to you!
