### ISSUE TITLE
Got Error when Make build

### ISSUE THREAD

**Issue by exodia0x** [grafana/xk6-websockets#50]
![image](https://github.com/grafana/xk6-websockets/assets/38641615/70123ff1-0d89-4396-8d2e-bceab6b01977)

OS: Macos
Go: go1.20.7 darwin/arm64
K6: k6 v0.45.0 ((devel), go1.20.5, darwin/arm64)

**Comment by codebien** [comment]
Hey @exodia0x, thanks for reporting the issue.
The command should now work. Let me know if doesn't work as expected.
