### ISSUE TITLE
Need support for []uint8

### ISSUE THREAD

**Issue by pixeldrew** [grafana/xk6-websockets#75]
Currently trying to write tests for a [YJS](https://yjs.dev) [socket](https://github.com/yjs/y-websocket) implementation.

I've managed to convert the yjs-socket library so that it works in goja, but i've hit a wall in that it transfers binary data via a Uint8Array. Right now this library doesn't support it that type. Since it's just a binary type represented as an array of 8-bit unsigned integers, shouldn't this be possible to do? 

add this to the [case statement here](https://github.com/grafana/xk6-websockets/blob/main/websockets/websockets.go#L594)
```go
case sobek.Uint8Array:
		w.bufferedAmount += len(o)
		w.writeQueueCh <- message{
			mtype: websocket.BinaryMessage,
			data:  o,
			t:     time.Now(),
		}

```
this is a guess, but it seems that it should work?

**Comment by mstoykov** [comment]
Thank you for reporting this @pixeldrew 🙇

It seems this is part of the [specification](https://websockets.spec.whatwg.org/#dom-websocket-send) that was missed
