### ISSUE TITLE
Experimental Websocket `readyState` returned as a string

### ISSUE THREAD

**Issue by dougw-bc** [grafana/xk6-websockets#79]
### Brief summary

The experimental websocket encodes its internal `readyState` as a string.

https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState

In a browser this value is represented as an integer. 

### k6 version

v0.53.0

### OS

Ubuntu, Windows 11

### Docker version and image (if applicable)

N/A

### Steps to reproduce the problem

Try to compare readyState to an integer, and it will not work as expected

### Expected behaviour

`WebSocket.readyState` should expose integers rather than string values.

### Actual behaviour

`WebSocket.readyState` returns a String instead of Integer

**Comment by mstoykov** [comment]
@dougw-bc can you please provide an exampe of this as it seems like the implementaiton is with integers and that has been the case for the last 2 years at least.

Are you sure you are not runnign a particularly old version of k6.

**Comment by dougw-bc** [comment]
I noticed this when trying to test an [Elixir Phoenix Channel](https://hexdocs.pm/phoenix/channels.html) websocket server.

Here is the code that was not functioning as expected on k6:

https://github.com/phoenixframework/phoenix/blob/main/assets/js/phoenix/socket.js#L525-L532

Updating this constant: https://github.com/phoenixframework/phoenix/blob/main/assets/js/phoenix/constants.js#L5 now behaves 'correctly'

```js
// BEFORE (not working as expected)
export const SOCKET_STATES = {connecting: 0, open: 1, closing: 2, closed: 3}

// AFTER works as expected
export const SOCKET_STATES = {connecting: "0", open: "1", closing: "2", closed: "3"}
```


Here is a reproduction of the issue with a small script:


```js
import { WebSocket } from "k6/experimental/websockets";

export const options = {
  vus: 1,
  iterations: 1,
};

function connectionState(state) {
  switch (state) {
    case 0:
      return "connecting";
    case 1:
      return "open";
    case 2:
      return "closing";
    case 3:
      return "closed";
    default:
      return "uh oh";
  }
}

export default async () => {
  const url = "wss://test-api.k6.io/ws/crocochat/publicRoom/";
  const socket = new WebSocket(url);

  socket.onopen = () => {
    console.log("connected! ", connectionState(socket.readyState));
  };

  socket.onclose = () => {
    console.log("closed! ", connectionState(socket.readyState));
  };

  console.log(connectionState(socket.readyState));

  const checkInterval = setInterval(() => {
    console.log(connectionState(socket.readyState));
  }, 250);

  setTimeout(function () {
    console.log(`Closing the socket`);
    socket.close();
    clearInterval(checkInterval);
  }, 3000);
};
```

My logs look like this:

```
INFO[0000] uh oh                                         source=console
INFO[0000] uh oh                                         source=console
INFO[0000] connected!  uh oh                     source=console
INFO[0000] uh oh                                         source=console
INFO[0000] uh oh                                         source=console
INFO[0001] uh oh                                         source=console
INFO[0001] uh oh                                         source=console
INFO[0001] uh oh                                         source=console
INFO[0001] uh oh                                         source=console
INFO[0002] uh oh                                         source=console
INFO[0002] uh oh                                         source=console
INFO[0002] uh oh                                         source=console
INFO[0002] uh oh                                         source=console
INFO[0003] Closing the socket                     source=console
INFO[0003] closed!  uh oh                            source=console
```

**Comment by dougw-bc** [comment]
After further testing - there might be something else going on with the `switch` statement itself - as this seems to work as expected:
Maybe this is a bug with `switch`?

```js
const vals = { 0: "connecting", 1: "open", 2: "closing", 3: "closed" };

function connectionState(state) {
  return vals[state] || "uh oh";
}
```

**Comment by mstoykov** [comment]
Whank you for reportuing this 🙇 

I managed to reproduce it and it seems to be a Sobek/goja bug where if you have type that is uint8 under the hood and return it goja/Sobek makes it into a string instead. But if you just return uint8 it works ... 🤦 

I will try to go further to fix it in the goja/Sobek code, but until then I have made #80
